package enums;


public enum ChangeEvent {
    USER_DATA,
    FRIEND_REQUEST_DATA,
    FRIENDSHIP_DATA,
    MESSAGE_EVENT,
    EVENT_SAVED,
    EVENT_DELETED,
    USER_SUBSCRIBED,
    NOTIFICATION,
}
